🔧 Tweak info upon installing in CLI

diff --git a/vscode/bin/code-extensions b/vscode/bin/code-extensions
--- a/vscode/bin/code-extensions
+++ b/vscode/bin/code-extensions
@@ -3,10 +3,15 @@ cliname="code-extensions"
 
 
 # Colors
+FAT='\033[0;1;37m'
 RED='\033[0;1;31m'
+REDTHIN='\033[0;31m'
 GREEN='\033[0;1;32m'
+GREENTHIN='\033[0;32m'
 YELLOW='\033[0;1;33m'
+YELLOWTHIN='\033[0;33m'
 BLUE='\033[0;1;34m'
+BLUETHIN='\033[0;34m'
 NC='\033[0m'
 
 source $DOTFILES/helpers/colors
@@ -27,7 +32,7 @@ A small script to help backup and install extensions for Visual Studio Code
     $cliname  backup  [--filename <file>]
 
  Options:
-  -f <file>, --filename <file>  Filename to backup or install from. ${YELLOW}[default: ${filename}]${NC}.
+  -f <file>, --filename <file>  Filename to backup or install from. ${FAT}[default: ${filename}]${NC}.
   -i, --interactive             Interactive mode.
   -h, --help                    Display this help and exit.
 "
@@ -42,11 +47,47 @@ _backup(){
 }
 
 _install(){
-    echo "Installing extensions from $filename"
+    if [ ! -f $filename ]; then
+        printf "${RED}Error:\t'$filename' File does not exist, or is not a regular file.\n"
+        exit 1
+    fi 
+    printf "${GREENTHIN}Installing extensions from file: ${YELLOW}$filename${NC}\n\n"
+    oldifs="$IFS"
+    IFS=$'\n'
+    output=()
     for i in `cat $filename`; do
-        code --install-extension $i;
+        printf "\033[1A\r\033[0K${GREEN}[INSTALLING]:${BLUETHIN} $i ${NC}\n"
+        output+=(`code --install-extension $i 2>&1 | grep Extension`)
     done
-    printf "${GREEN}Installation complete${NC}"
+    IFS="$oldifs"
+    printf "\033[1A\r\033[0K"
+    alr=0
+    newversion=0
+    err=0
+    for each in "${output[@]}"; do
+        # Count already installed
+        if [[ $each =~ already ]]; then
+            (( alr++ ))
+            if [[ $each =~ newer ]]; then
+                ((newversion++))
+            fi
+        # Count errors
+        elif [[ $each =~ Failed ]]; then
+        (( err++ ))
+        fi
+    done 
+    # Installed - already - errors
+    new=$((${#output[@]}-$alr-$err))
+    # Result print
+    printf "${BLUE}Installation of ${#output[@]} extensions completed with:${NC}\n"
+    printf "${GREENTHIN}✓ $new installations${NC}\n"
+    printf "${YELLOWTHIN}• $alr extensions already installed"
+    if [ $newversion != 0 ]; then
+        printf "${YELLOWTHIN}, $newversion have available updates${NC}\n"
+    else
+        printf "${NC}\n"
+    fi
+    printf "${REDTHIN}✖ $err errored\n"
 }
 
 backuporinstall(){
@@ -125,7 +166,7 @@ if [ "$backup" = 1 -a "$install" = 1 ]; then
 fi
 
 
-if [ "$interactive" = "1" ]; then
+if [ $interactive = 1 ]; then
     printf "${GREEN}Welcome! Let's get started with managing extensions${NC}\n\n"
     backuporinstall
     getfilename
